# Generated by Django 4.2.28 on 2026-02-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="gdrive_file_id",
        ),
    ]
