# Generated by Django 4.2.23 on 2025-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_url_alter_book_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='dropbox_path',
            new_name='gdrive_file_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
